// Question bank: 50 serious, 50 fun, 50 normal
export const questionBank = {
  serious: [
    "Điều gì khiến bạn hối tiếc nhất trong cuộc sống?",
    "Nếu còn 1 năm để sống, bạn sẽ làm gì?",
    "Điều gì khiến bạn sợ hãi nhất?",
    "Bạn định nghĩa thành công là gì?",
    "Điều gì khiến bạn cảm thấy cô đơn nhất?",
    "Bạn muốn được nhớ đến như thế nào sau khi mất đi?",
    "Điều bí mật nào bạn chưa kể với ai?",
    "Bạn đã tha thứ cho ai khó nhất trong đời?",
    "Điều gì khiến bạn khóc gần đây nhất?",
    "Bạn nghĩ ý nghĩa của cuộc sống là gì?",
    "Khoảnh khắc nào trong đời bạn muốn quay lại?",
    "Bạn đã từng phá vỡ lòng tin của ai chưa?",
    "Điều gì khiến bạn mất ngủ vào ban đêm?",
    "Bạn sợ thất bại hay sợ không thử hơn?",
    "Điều bạn tự hào nhất về bản thân là gì?",
    "Bạn đã từng cảm thấy vô dụng chưa? Khi nào?",
    "Điều gì khiến bạn cảm thấy sống có ý nghĩa?",
    "Bạn muốn con cái (hoặc thế hệ sau) học gì từ bạn?",
    "Điều gì bạn ước mình có thể nói với phiên bản 10 tuổi của mình?",
    "Bạn nghĩ ai thực sự hiểu bạn nhất?",
    "Điều gì bạn chưa bao giờ dám thú nhận với gia đình?",
    "Bạn đã bao giờ cảm thấy mình đang sống sai cuộc đời chưa?",
    "Kỳ vọng lớn nhất của bạn với chính mình là gì?",
    "Điều gì khiến bạn cảm thấy không xứng đáng?",
    "Bạn đã bao giờ xin lỗi ai mà họ không bao giờ biết chưa?",
    "Điều gì bạn muốn thay đổi về thế giới này?",
    "Bạn có tin vào tình yêu đích thực không?",
    "Khoảnh khắc nào khiến bạn nhận ra mình đã trưởng thành?",
    "Điều gì bạn hy sinh nhiều nhất trong cuộc sống?",
    "Bạn nghĩ bạn bè thật sự của bạn là ai?",
    "Điều gì bạn sợ nhất khi già đi?",
    "Bạn đã bao giờ muốn biến mất khỏi tất cả chưa?",
    "Điều gì khiến bạn tiếp tục cố gắng dù mệt mỏi?",
    "Bạn nghĩ tình bạn hay tình yêu quan trọng hơn?",
    "Điều gì bạn chưa bao giờ dám thú nhận với bạn bè?",
    "Bạn đã bao giờ cảm thấy phản bội ai chưa?",
    "Điều gì khiến bạn mạnh mẽ hơn mỗi ngày?",
    "Bạn muốn ai đó hiểu điều gì về bạn nhất?",
    "Điều gì bạn nghĩ mình giỏi nhưng thực ra không giỏi?",
    "Kỳ vọng của gia đình có làm bạn áp lực không?",
    "Điều gì bạn chưa bao giờ làm vì sợ thất bại?",
    "Bạn có hài lòng với con người mình hiện tại không?",
    "Điều gì khiến một mối quan hệ trở nên bền vững?",
    "Bạn đã từng yêu ai mà không dám nói không?",
    "Điều gì bạn muốn thay đổi về quá khứ của mình?",
    "Bạn nghĩ lòng tốt có được đền đáp không?",
    "Điều gì bạn cần nhưng chưa bao giờ xin?",
    "Bạn đã bao giờ làm tổn thương ai mà không cố ý không?",
    "Điều gì bạn học được từ thất bại lớn nhất?",
    "Bạn sống cho hiện tại hay cho tương lai hơn?",
    "Điều gì khiến bạn thực sự sợ hãi trong cuộc sống?",
    "Bạn nghĩ ý nghĩa thực sự của cuộc sống là gì?",
    "Nếu biết mình chỉ còn 1 năm để sống, bạn sẽ làm gì?",
    "Điều gì khiến bạn cảm thấy hối tiếc nhất trong cuộc đời?",
    "Bạn định nghĩa thành công theo nghĩa nào?",
    "Điều gì khiến bạn mất niềm tin vào con người?",
    "Bạn có sợ cô đơn không? Tại sao?",
    "Nếu có thể thay đổi một quyết định trong quá khứ, bạn sẽ chọn điều gì?",
    "Bạn nghĩ đạo đức và luật pháp có luôn đi đôi với nhau không?",
    "Điều gì khiến bạn tiếp tục cố gắng khi mọi thứ trở nên khó khăn?",
    "Bạn có tin vào số phận không? Tại sao?",
    "Điều bạn chưa bao giờ nói với ai là gì?",
    "Bạn nghĩ con người về bản chất là tốt hay xấu?",
    "Nếu có thể nói chuyện với phiên bản 10 năm trước của mình, bạn sẽ nói gì?",
    "Điều gì khiến bạn cảm thấy cuộc sống có giá trị?",
    "Bạn có bao giờ cảm thấy mình đang sống không đúng với con người thật của mình không?",
    "Theo bạn, tình yêu hay sự nghiệp quan trọng hơn?",
    "Bạn nghĩ mối quan hệ gia đình ảnh hưởng đến bạn như thế nào?",
    "Nếu tiền không phải vấn đề, bạn sẽ làm gì với cuộc đời mình?",
    "Điều gì khiến bạn cảm thấy mình đang lãng phí thời gian?",
    "Bạn có tin vào sự tha thứ hoàn toàn không?",
    "Điều gì là ranh giới không thể vượt qua trong mối quan hệ của bạn?",
    "Bạn nghĩ sự thật hay lòng tốt quan trọng hơn khi phải chọn?",
    "Điều bạn sợ nhất khi già đi là gì?",
    "Bạn có bao giờ cảm thấy mình không thuộc về nơi mình đang sống không?",
    "Theo bạn, hạnh phúc là trạng thái cảm xúc hay là lựa chọn?",
    "Điều gì khiến bạn mất ngủ vào ban đêm?",
    "Bạn có nghĩ rằng mọi người đều xứng đáng được yêu thương không?",
    "Điều gì định hình nên con người bạn ngày hôm nay nhiều nhất?",
    "Bạn nghĩ cái chết là kết thúc hay là sự bắt đầu của điều gì đó?",
    "Bạn có bao giờ cảm thấy mình đang mang một gánh nặng mà không ai biết không?",
    "Theo bạn, sự trung thực có thể gây hại không?",
    "Điều gì làm bạn cảm thấy không được thấu hiểu?",
    "Bạn có bao giờ tự hỏi mình có đang sống đúng với giá trị của mình không?",
    "Nếu có thể biết trước tương lai, bạn có muốn biết không? Tại sao?",
    "Bạn nghĩ sự cô đơn và sự một mình khác nhau như thế nào?",
    "Điều gì khiến bạn cảm thấy mình trưởng thành nhất?",
    "Bạn có tin rằng mọi việc xảy ra đều có lý do không?",
    "Điều bạn ước mình học được sớm hơn trong cuộc sống là gì?",
    "Bạn nghĩ sự hi sinh trong tình yêu có giới hạn không?",
    "Điều gì khiến bạn cảm thấy thực sự sống?",
    "Bạn có bao giờ tự hỏi liệu mình có đang đủ tốt chưa không?",
    "Nếu phải chọn giữa sự giàu có và sự bình yên, bạn chọn gì?",
    "Bạn nghĩ lòng biết ơn thay đổi cuộc sống của một người như thế nào?",
    "Điều gì khiến bạn cảm thấy mình đang đi đúng hướng?",
    "Bạn có sợ thất bại đến mức không dám thử không?",
    "Theo bạn, tình bạn thật sự có tồn tại mãi mãi không?",
    "Điều bạn muốn được nhớ đến sau khi mất là gì?",
    "Bạn nghĩ sự thay đổi là điều đáng sợ hay đáng mong chờ?",
    "Bạn có bao giờ cảm thấy mình đang chạy trốn khỏi điều gì đó không?"
  ],
  fun: [
    "Nếu được biến thành một con vật, bạn muốn là con gì và tại sao?",
    "Bạn sẽ chọn siêu năng lực nào: bay hay tàng hình?",
    "Nếu cuộc đời bạn là phim, phim đó thuộc thể loại gì?",
    "Bạn muốn cưỡi con vật gì ra trận?",
    "Nếu được làm thực phẩm, bạn muốn là món ăn nào?",
    "Bạn sẽ làm gì nếu tỉnh dậy và có đuôi?",
    "Nếu được chọn nhạc nền cho cuộc đời, bạn chọn bài gì?",
    "Bạn nghĩ ai trong nhóm này có thể sống sót ở đảo hoang?",
    "Nếu mỗi lần nói dối thì mũi dài ra như Pinocchio, cuộc sống bạn sẽ thế nào?",
    "Bạn sẽ làm gì nếu robot Doraemon là bạn cùng phòng?",
    "Nếu phải hét một câu ở nơi công cộng, bạn hét gì?",
    "Bạn muốn đổi tên thành gì nếu được chọn lại?",
    "Nếu có thể nói chuyện với động vật, bạn hỏi con gì đầu tiên?",
    "Bạn sẽ làm gì nếu vô tình được thăng chức thành Tổng thống?",
    "Kỹ năng vô dụng nhất của bạn là gì?",
    "Nếu bạn là meme, bạn là meme nào?",
    "Bạn sẽ làm gì trong 24 giờ đầu tiên nếu vô hình?",
    "Món ăn nào bạn có thể ăn mãi không chán?",
    "Nếu tất cả mọi người biết được lịch sử tìm kiếm của bạn, bạn sẽ nói gì?",
    "Bạn nghĩ mình sẽ chết vì lý do ngốc nghếch gì nhất?",
    "Nếu được xóa một thứ khỏi thế giới, bạn chọn gì?",
    "Bạn sẽ nói gì với khủng long nếu gặp ngoài đời thực?",
    "Điều kỳ lạ nhất bạn từng nhìn thấy trên đường phố là gì?",
    "Nếu mỗi buổi sáng thức dậy có nhạc nền, bạn chọn bài gì?",
    "Bạn sẽ làm gì đầu tiên nếu trúng số 10 tỷ?",
    "Nếu ăn một thứ mà không béo mãi mãi, bạn chọn gì?",
    "Thói quen xấu hài hước nhất của bạn là gì?",
    "Bạn sẽ dạy AI điều gì đầu tiên nếu có thể?",
    "Nếu cuộc sống có nút Undo, bạn undo điều gì gần nhất?",
    "Bạn đặt tên cho giường ngủ của mình là gì?",
    "Nếu phải tham gia show truyền hình thực tế, bạn chọn show nào?",
    "Bạn nghĩ người ngoài hành tinh sẽ sợ nhất điều gì ở Trái Đất?",
    "Nếu được làm thầy giáo, bạn dạy môn gì?",
    "Điều nhảm nhí nhất bạn từng lo lắng là gì?",
    "Nếu bạn là nhân vật hoạt hình, bạn là ai?",
    "Bạn sẽ làm gì nếu thức dậy và biết 10 thứ tiếng?",
    "Điều buồn cười nhất xảy ra với bạn gần đây là gì?",
    "Nếu được ra lệnh cho mọi người làm một điều, bạn chọn gì?",
    "Bạn sẽ nói gì nếu gặp phiên bản tương lai của mình?",
    "Thứ gì bạn không thể hiểu dù đã nghe giải thích nhiều lần?",
    "Nếu phải chọn một bài hát làm nhạc kẹt thang máy, bạn chọn bài gì?",
    "Bạn sẽ làm gì nếu có phân thân?",
    "Điều ngớ ngẩn nhất bạn từng tin khi còn nhỏ là gì?",
    "Nếu thức ăn có cảm xúc, thứ nào sẽ buồn nhất vì bị ăn?",
    "Bạn nghĩ mình có thể làm nghề gì kỳ lạ nhất?",
    "Nếu được phép đặt quy tắc cho cả nhóm, bạn đặt quy tắc gì?",
    "Điều bạn nghĩ chỉ có mình bạn mới làm vậy là gì?",
    "Nếu buộc phải mặc một bộ đồ suốt đời, bạn chọn gì?",
    "Bạn sẽ làm gì nếu biết mai là ngày tận thế?",
    "Nếu bạn có thể xây dựng ngôi nhà ở bất kỳ đâu, bạn chọn nơi nào?",
    "Nếu được làm động vật trong 1 ngày, bạn chọn con gì và tại sao?",
    "Siêu năng lực vô dụng nhất mà bạn muốn có là gì?",
    "Bạn sẽ làm gì nếu bỗng nhiên trở thành tổng thống trong 1 tiếng?",
    "Món ăn nào bạn có thể ăn cả đời mà không chán?",
    "Nếu cuộc sống của bạn là một bộ phim, tên phim đó sẽ là gì?",
    "Bạn sẽ dùng 1 tỷ đồng vào việc ngốc nghếch nhất là gì?",
    "Nếu được đổi tên, bạn sẽ đặt tên mình là gì?",
    "Bạn sẽ làm gì nếu thức dậy và thấy mình cao 3 mét?",
    "Kỹ năng vô nghĩa nhất bạn thực sự có là gì?",
    "Nếu chó và mèo có thể nói chuyện, chúng sẽ nói gì về bạn?",
    "Bạn sẽ tồn tại được bao lâu trong phim zombie?",
    "Nếu phải ăn một loại pizza kỳ lạ nhất, bạn chọn topping gì?",
    "Nhân vật hoạt hình nào bạn nghĩ sẽ là bạn thân tệ nhất?",
    "Nếu có thể nói chuyện với đồ vật trong nhà, bạn sẽ hỏi gì đầu tiên?",
    "Bạn sẽ làm gì nếu phát hiện nhà hàng xóm là robot?",
    "Loại nhạc nào sẽ phát liên tục nếu cuộc đời bạn có soundtrack?",
    "Nếu phải chiến đấu với 100 con vịt cỡ gà, bạn làm thế nào?",
    "Bạn sẽ đặt tên gì cho một con ngựa nếu bạn có một con?",
    "Nếu được phép phá một quy tắc xã hội mà không bị phán xét, bạn chọn gì?",
    "Bạn nghĩ mình trông như thế nào khi ngủ?",
    "Nếu các hành tinh trong hệ mặt trời là người, bạn sẽ kết bạn với ai?",
    "Bạn sẽ làm gì nếu được vô hình trong 1 giờ?",
    "Thứ tệ nhất bạn từng nấu là gì?",
    "Nếu phải mặc một bộ đồ cả đời, bạn chọn gì?",
    "Loài vật nào bạn nghĩ bí ẩn nhất và tại sao?",
    "Bạn sẽ làm gì nếu bỗng nhiên quên hết cách đi bộ?",
    "Nếu bạn là một loại thức uống, bạn là gì?",
    "Câu hỏi ngớ ngẩn nhất bạn từng Google là gì?",
    "Bạn nghĩ ai trong nhóm bạn sẽ sống sót được trên đảo hoang lâu nhất?",
    "Nếu mưa không phải là nước mà là một thứ khác, bạn muốn nó là gì?",
    "Bạn sẽ đặt tên cửa hàng của mình là gì nếu nó bán thứ hoàn toàn vô nghĩa?",
    "Nhân vật phản diện nào trong phim bạn thấy... có lý?",
    "Nếu không cần ngủ, bạn sẽ dùng thời gian đó để làm gì?",
    "Bạn sẽ làm gì nếu phát hiện ra mèo có thể đọc suy nghĩ của bạn?",
    "Loại rau nào bạn nghĩ xứng đáng biến mất khỏi trái đất nhất?",
    "Nếu được thêm một nút trên điện thoại, nút đó làm gì?",
    "Bạn sẽ làm gì nếu sáng ngủ dậy và phát hiện mình đổi thân xác với sếp?",
    "Nếu phim hoạt hình nào đó là thật, bạn muốn sống trong thế giới nào?",
    "Điều gì sẽ xảy ra nếu mọi người đều nói thật trong vòng 24 giờ?",
    "Bạn sẽ làm gì nếu robot hút bụi nhà bạn bắt đầu nói chuyện?",
    "Nếu phải chọn một bài nhạc phát mỗi khi bước vào phòng, bạn chọn bài gì?",
    "Loại siêu anh hùng kỳ lạ nhất bạn có thể nghĩ ra là gì?",
    "Bạn sẽ phản ứng thế nào nếu gặp bản sao của mình ngoài đường?",
    "Nếu động vật được bầu cử, con nào sẽ làm tổng thống?",
    "Bạn sẽ làm gì nếu trọng lực đột nhiên giảm đi một nửa?",
    "Màu sắc nào bạn nghĩ có mùi và mùi đó là gì?",
    "Nếu bạn là thám tử, bí danh của bạn là gì?",
    "Bạn sẽ viết gì trên bia mộ của mình nếu được tự chọn?",
    "Loại trò chơi nào bạn chắc chắn sẽ thua nếu thi đấu với trẻ em?",
    "Nếu tiếng cười của bạn là một âm thanh khác, nó sẽ là âm thanh gì?"
  ],
  normal: [
    "Sở thích lớn nhất của bạn là gì?",
    "Bạn thích đi du lịch hay ở nhà?",
    "Món ăn yêu thích của bạn là gì?",
    "Bạn thức khuya hay dậy sớm?",
    "Bộ phim nào bạn yêu thích nhất?",
    "Bạn thích mùa nào trong năm?",
    "Bạn thường làm gì vào cuối tuần?",
    "Bạn đã từng đi du lịch nước ngoài chưa?",
    "Loại nhạc nào bạn hay nghe?",
    "Bạn thích đọc sách hay xem phim?",
    "Điều bạn muốn học thêm trong năm tới là gì?",
    "Bạn thích cà phê hay trà?",
    "Công việc mơ ước của bạn khi còn nhỏ là gì?",
    "Bạn có nuôi thú cưng không?",
    "Người truyền cảm hứng cho bạn nhất là ai?",
    "Bạn thích thể thao hay nghệ thuật?",
    "Bạn hay dành thời gian rảnh làm gì?",
    "Điều bạn tự hào nhất gần đây là gì?",
    "Bạn có kế hoạch gì cho năm sau?",
    "Bạn thích ăn ở nhà hay ăn ngoài hàng?",
    "Bạn thích mưa hay nắng?",
    "Loại phim bạn hay xem nhất là gì?",
    "Bạn thường ngủ mấy tiếng một đêm?",
    "Điều bạn muốn thay đổi trong thói quen hàng ngày là gì?",
    "Bạn có hay nấu ăn không?",
    "Mục tiêu lớn nhất của bạn trong 5 năm tới là gì?",
    "Bạn thích mua sắm online hay trực tiếp?",
    "Bạn có hay đọc tin tức không?",
    "Điều bạn làm đầu tiên khi thức dậy là gì?",
    "Bạn thích làm việc nhóm hay làm việc một mình?",
    "Bạn háo hức nhất về điều gì trong cuộc sống?",
    "Loài hoa nào bạn thích nhất?",
    "Bạn thích khách sạn sang trọng hay nhà nghỉ bình dân?",
    "Bạn có hay tập thể dục không?",
    "Bạn thích cuối tuần ở thành phố hay về quê?",
    "Điều khiến bạn cảm thấy thoải mái nhất là gì?",
    "Bạn hay mua quà cho bản thân không?",
    "Bạn thích ăn cay hay không cay?",
    "Ứng dụng điện thoại nào bạn dùng nhiều nhất?",
    "Bạn hay mơ về điều gì?",
    "Điều bạn thích nhất về công việc/học tập hiện tại là gì?",
    "Bạn thường đi ngủ lúc mấy giờ?",
    "Bạn thích môn học nào nhất hồi đi học?",
    "Bạn có hay nói chuyện với người lạ không?",
    "Bạn thích xem thể thao hay chơi thể thao?",
    "Điều bạn mua gần đây mà hài lòng nhất là gì?",
    "Bạn có kế hoạch du lịch nào sắp tới không?",
    "Bạn thích nghe podcast hay xem YouTube?",
    "Điều nhỏ nhặt nào khiến bạn vui mỗi ngày?",
    "Bạn thích tổ chức tiệc hay đến tiệc của người khác?",
    "Bạn thích dậy sớm hay thức khuya?",
    "Món ăn yêu thích của bạn là gì?",
    "Bạn thích đi du lịch một mình hay cùng bạn bè?",
    "Bạn có thói quen gì vào buổi sáng?",
    "Thể loại phim bạn thích xem nhất là gì?",
    "Bạn thích cà phê hay trà?",
    "Cuốn sách bạn đọc gần đây nhất là gì?",
    "Bạn thích biển hay núi?",
    "Mùa nào trong năm bạn thích nhất?",
    "Bạn có sở thích gì ngoài công việc?",
    "Bạn thường dành cuối tuần như thế nào?",
    "Ứng dụng bạn dùng nhiều nhất trên điện thoại là gì?",
    "Bạn thích âm nhạc thể loại gì?",
    "Bạn có nuôi thú cưng không?",
    "Bạn thích nấu ăn tại nhà hay ra ngoài ăn?",
    "Chương trình TV hoặc series bạn đang xem là gì?",
    "Bạn có thói quen thể dục không? Bạn tập gì?",
    "Bạn thích mua sắm online hay trực tiếp?",
    "Điểm đến du lịch trong mơ của bạn là gì?",
    "Bạn thích làm việc một mình hay trong nhóm?",
    "Loại thời tiết nào bạn cảm thấy thoải mái nhất?",
    "Bạn thường nghe nhạc khi làm gì?",
    "Bạn có hay nấu ăn không? Bạn nấu giỏi món gì?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bạn có thích đọc tin tức hằng ngày không?",
    "Phim hoặc series nào bạn có thể xem đi xem lại nhiều lần?",
    "Bạn thường đi ngủ lúc mấy giờ?",
    "Bạn có hay mua đồ uống ngoài hay tự pha tại nhà?",
    "Bạn thích không gian làm việc yên tĩnh hay có tiếng ồn nhẹ?",
    "Bạn có hay lên kế hoạch trước hay thích sự ngẫu hứng?",
    "Loại snack bạn hay ăn vặt là gì?",
    "Bạn dùng mạng xã hội nào nhiều nhất?",
    "Bạn thích nhận quà tặng bất ngờ hay được hỏi trước?",
    "Bạn có hay xem YouTube không? Kênh nào bạn hay xem nhất?",
    "Bạn thích đi bộ hay đi xe khi di chuyển gần?",
    "Buổi tối bạn thường làm gì để thư giãn?",
    "Bạn có hay nói chuyện điện thoại dài không?",
    "Kỹ năng nào bạn tự hào nhất?",
    "Bạn thích học qua sách, video hay tự thực hành?",
    "Bạn hay quên mang theo thứ gì nhất?",
    "Bạn có hay uống đủ nước mỗi ngày không?",
    "Thứ đầu tiên bạn làm khi thức dậy là gì?",
    "Bạn có hay viết nhật ký hoặc ghi chú không?",
    "Bạn thích sinh nhật kiểu tiệc lớn hay nhỏ gọn?",
    "Bạn có hay theo dõi thời tiết trước khi ra ngoài không?",
    "Kiểu người nào bạn dễ kết bạn nhất?",
    "Bạn thường mất bao lâu để quyết định ăn gì?",
    "Bạn có hay xem lại ảnh cũ không?",
    "Bạn thích nhà gọn gàng hay có thể hơi bừa bộn?",
    "Khi buồn, bạn thường làm gì để cảm thấy tốt hơn?"
  ]
}

export function getRandomQuestion(type) {
  const pool = questionBank[type]
  if (!pool || pool.length === 0) return ''
  return pool[Math.floor(Math.random() * pool.length)]
}
